numbered_command = false

use_trash = false
watch_files = true
xdg_open = false
xdg_open_fork = false


[display]
# default, hsplit
mode = "default"

automatically_count_files = true
collapse_preview = true
# ratios for parent view (optional), current view and preview
column_ratio = [1, 3, 4]
scroll_offset = 6
show_borders = false
show_hidden = false
show_icons = true
# Shorten /home/$USER to ~
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "none"

[display.sort]
# Options include
# - lexical  (10.txt comes before 2.txt)
# - natural  (2.txt comes before 10.txt)
# - mtime
method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 2097152 # 2MB
preview_script = "~/.config/joshuto/preview_file.sh"

[tab]
# inherit, home, root
home_page = "home"
