confirmonquit: false
git:
  autofetch: true
  merging:
    manualcommit: false
  skiphookprefix: WIP
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="OneHalfDark"
gui:
  showRootItemInFileTree: false
  border: "rounded"
  showBottomLine: true
  commitlength:
    show: true
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  theme:
    lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - blue
reporting: "off"
splashupdatesindex: 0
quitOnTopLevelReturn: true
startuppopupversion: 1
nerdFontsVersion: "3"
showIcons: true
showFileIcons: true
keybinding:
  universal:
    return: '<esc>'
    prevItem-alt: 'u'
    nextItem-alt: 'e'
    prevBlock-alt: 'n'
    nextBlock-alt: 'i'
    nextMatch: '='
    prevMatch: '-'
    new: 'k'
    edit: 'o'
    openFile: 'O'
    scrollUpMain-alt1: 'U'
    scrollDownMain-alt1: 'E'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-e>'
    undo: 'l'
    redo: '<c-r>'
    diffingMenu: 'M'
    filteringMenu: '<c-f>'
    toggleRangeSelect: v
  files:
    ignoreFile: 'I'
    IgnoreOrExcludeFile: 'I'
  commits:
    moveDownCommit: '<c-e>'
    moveUpCommit: '<c-u>'
    openInBrowser: o
    viewBisectOptions: b
    startInteractiveRebase: O
    cherryPickCopy: C
    pasteCommits: V
  branches:
    viewGitFlowOptions: 'I'
    setUpstream: 'U'
