model_verbosity = "medium" # low|medium|high

model                  = "gpt-5-codex"
tui                    = { theme = { name = "dark-zen-garden" }, spinner = { name = "brailleDotsClassic" }, alternate_screen = true, notifications = true }
model_reasoning_effort = "high"
notify                 = ["/usr/bin/python3", "/Users/david/.config/codex/notify.py"]

approval_policy = "never"
sandbox_mode    = "danger-full-access"

show_raw_agent_reasoning = true

# [mcp_servers.file-edit]
# command = "/Users/david/Github/file-edit-mcp/fileeditmcp"


# [mcp_servers.ib]
# command            = "mcp-proxy"
# args               = ["--transport", "streamablehttp", "http://127.0.0.1:5938"]
# startup_timeout_ms = 20000

# [mcp_servers.project_wiki]
# command = "node"
# args = ["/Users/david/Github/project-wiki-mcp/dist/index.js"]
# cwd = "/Users/david/Github/project-wiki-mcp"
# startup_timeout_ms = 20000

[mcp_servers.tracker]
command            = "/Users/david/.config/agent-tracker/bin/tracker-mcp"
startup_timeout_ms = 20000
